### PR TITLE
fix libsplit benchmark: POSIX compatibility

### LINKED ISSUE #530: libsplit benchmark script is bash dependent
The benchmark script introduced in 15657e4d seems to be dependent on bash. When executed with the shebang provided it throws the following error on my development system (Debian 7.9):

```libelektra/scripts/benchmark_libsplit.sh: 18: libelektra/scripts/benchmark_libsplit.sh: Syntax error: Missing '))'```

The issue seems to be rooted in the line ```WALLTIME=$((time -p $BENCHMARK) 2>&1)```.
Can anyone confirm this issue?

### PR DESCRIPTION
**Pull request by mpranj**
Should fix #530 .

Tested on FreeBSD which is:
> close to the IEEE	Std 1003.1 (``POSIX.1'')

Prints just to stdout now, instead of creating logfiles which I have used to evaluate the results in R.

### CODE REVIEW

File: scripts/benchmark_libsplit.sh [hunk 1]
```diff
@@ -6,13 +6,13 @@ fi
...
-
-echo "Runtime as IEEE Std 1003.2-1992 (``POSIX.2'')" >> $LOGFILE
-for run in {0..20}; do
-	echo "RUN: #$run"
-	WALLTIME=$((time -p $BENCHMARK) 2>&1)
-	echo $WALLTIME | awk -F"real" '{print $1;}' # print programs stdout
-	echo $WALLTIME | awk -F"real" '{print $2;}' | awk '{print $1;}' >> $LOGFILE
+echo "Runtime as IEEE Std 1003.2-1992 (``POSIX.2'')"
+echo "Doing $RUNS runs:"
+for run in $(seq 1 $RUNS); do
```
Comment (markus2330) [inline scripts/benchmark_libsplit.sh]: seq seems to not exist on OpenBSD #656 

So POSIX would be:

1. count manually: `i=$((i+1));`
2. use awk to generate the seq `awk "BEGIN{for (i = 1; i <= $RUNS; i ++) print i}"`

Maybe you can fix #656, too?

File: scripts/benchmark_libsplit.sh [hunk 2]
```diff
@@ -11,8 +11,10 @@ RUNS=21
 
 echo "Runtime as IEEE Std 1003.2-1992 (``POSIX.2'')"
 echo "Doing $RUNS runs:"
-for run in $(seq 1 $RUNS); do
+i=0
+while [ $i -lt $RUNS ] ; do
```
Comment (mpranj) [inline scripts/benchmark_libsplit.sh]: I'm not sure how this behaves on OpenBSD. It works on FreeBSD but it appears from the man-pages that they have different `/bin/sh` implementations.
