### PR TITLE
Cache fix synopsis

### LINKED ISSUE #3301: cache: fix tool synopsis
Synopsis was not updated, `kdb cache default` is missing here but available in the man page.

https://github.com/ElektraInitiative/libelektra/blob/b04c7f85a902fd247b628d88d752370d33dd034a/src/tools/kdb/cache.hpp#L26-L33

### PR DESCRIPTION
**Pull request by mpranj**
Closes #3301.

### CODE REVIEW

File: src/tools/kdb/cache.hpp [hunk 1]
```diff
@@ -25,17 +25,20 @@ class CacheCommand : public Command
...
 	virtual std::string getShortHelpText () override
 	{
-		return "Enable, disable or clear the cache.";
+		return "Enable, disable, clear the cache or revert to default.";
 	}
 
 	virtual std::string getLongHelpText () override
 	{
-		return "";
+		return "This command is used to enable or disable the cache and to revert\n"
```
Comment (markus2330) [inline src/tools/kdb/cache.hpp]: Afaik the getLongHelpText is no longer used. So it is better to leave it empty (or even better: remove the whole function in all the classes).

**Comment by markus2330** [comment]
Thank you for the PR!

File: src/tools/kdb/cache.hpp (hunk 1 above)
Comment (mpranj) [reply src/tools/kdb/cache.hpp]: My `kdb` tool displays the long help text. I can remove it in all classes, but likely not today.

Many tools do have some information in the long help text. Do we just throw that out, or is the idea to merge everything into one single help text, be it long or short?

Comment (markus2330) [reply src/tools/kdb/cache.hpp]: Yes, you are right. The text is shown when typing in wrong arguments or similar.

So then leave it as is, as it would be a lot of work to unify all these texts and there would be only little gain.
