### PR TITLE
keyname: fix bug with colon in cascading name

### LINKED ISSUE #4253: Keyname validation bug
## Steps to Reproduce the Problem

```sh
kdb get "system:/elektra/mountpoints/user:\\/test"
```

## Expected Result

`kdb` prints the value of `system:/elektra/mountpoints/user:\\/test` or 

```
Did not find key 'system:/elektra/mountpoints/user'
```

## Actual Result

```
The command bin/kdb get terminated unsuccessfully with the info:
Invalid Keyname: keyname needs to start with /, meta:/, default:/, spec:/, proc:/, dir:/, user:/ or system:/ or maybe you tried to change a key that is already in a KeySet. Name was: '/elektra/mountpoints/user:\/test' 
Please report the issue at https://issues.libelektra.org/
```

## System Information

- Elektra: master

## Further Log Files and Output

The problem seems to be this line, ~I'll submit a PR shortly.~ see #4254

https://github.com/ElektraInitiative/libelektra/blob/a778788ce46dab7bda92bda72e8a28850e521473/src/libs/elektra/keyname.c#L760

### PR DESCRIPTION
**Pull request by kodebach**
Fixes #4253

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

File: src/libs/elektra/keyname.c [hunk 1]
```diff
@@ -880,6 +886,8 @@ void elektraKeyNameCanonicalize (const char * name, char ** canonicalName, size_
 		if (*name != '/')
 		{
 			// find end of namespace
+			// compare to elektraKeyNameValidate we can just look for the :,
+			// becuase we know the name must be valid
```
Comment (markus2330) [inline src/libs/elektra/keyname.c:890]:
```suggestion
			// because we know the name must be valid
```

**Review by markus2330 — COMMENTED** [review]
Can you please also add offending test cases?
