### PR TITLE
Multifile error fixes

### LINKED ISSUE #2694: multiresolver: crash when used with cache
src/plugins/resolver/resolver.c:1175 seems to cause a crash in some situations.

Tried to reproduce. Does not work:

```sh
# create a new folder to not mess up with existing data
mkdir x
cd x

# create two mountpoints
kdb mount `pwd`/csv system/tests/csv/lists/cur csvstorage header=colname,columns/index=student/id
kdb mount -R multifile -c storage="ini",pattern="*/*",resolver="resolver" `pwd`/multi system/tests/multi

# create a csv file
echo "student/id,ue/5/kreuzerl" >> csv
echo "01234567,X" >> csv

# create a multiresolver directory
mkdir -p multi/pool
cd multi/pool
echo "[]" >> 01234567 >> 01234568 >> 01234569
echo "[student]" >> 01234567 >> 01234568 >> 01234569
echo "id = 01234567" >> 01234567
echo "[ue/5]" >> 01234567

 # create caches
kdb ls system/tests > /dev/null
kdb ls system/tests/multi/pool > /dev/null
kdb ls system/tests/csv/lists/cur > /dev/null

# now do something directly on the files
rm 01234569
touch 01234566
echo "kreuzerl = O" >> 01234567
echo "[something]" >> 01234567 >> 01234568
echo ""  >> 01234567 >> 01234568
echo ""  >> 01234568

# trigger
kdb cp -rf system/tests/csv/lists/cur system/tests/multi/pool

# debug
kdb export system/tests mini
tail *

kdb umount system/tests/csv/lists/cur
kdb umount system/tests/multi
cd ../../..
rm -r x
```

Did not work:

```sh
# create a new folder to not mess up with existing data
mkdir x
cd x

# create two mountpoints
kdb mount `pwd`/csv system/tests/csv csvstorage header=colname,columns/index=sec/somekey 
kdb mount -R multifile -c storage="ini",pattern="*",resolver="resolver" `pwd`/multi system/tests/multi

# create a csv file
echo "sec/somekey,othersec/deep/otherkey" >> csv
echo "a,data2a" >> csv
# echo "b,data2b" >> csv # but do not write in the other

# create a multiresolver directory
mkdir multi
cd multi
echo "[sec]" >> a >> b
echo "somekey = a" >> a
echo "somekey = b" >> b
echo "" >> a >> b
echo "" >> a >> b

kdb cp -rf system/tests/csv system/tests/multi

kdb umount system/tests/csv
kdb umount system/tests/multi
```

The problem seems to be `filename=0x2 <error: Cannot access memory at address 0x2>`, most likely set wrongly by the multiresolver?

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f902d39542a in __GI_abort () at abort.c:89
#2  0x0000564e84a716fc in catchSignal (signum=<optimized out>) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/tools/kdb/main.cpp:110
#3  <signal handler called>
#4  strlen () at ../sysdeps/x86_64/strlen.S:106
#5  0x00007f902d3a9da8 in _IO_vfprintf_internal (s=s@entry=0x7fffc1371d80, format=<optimized out>, format@entry=0x7f902c448ddd "the file \"%s\" because of \"%s\"", ap=ap@entry=0x7fffc1371f48) at vfprintf.c:1637
#6  0x00007f902d457cf6 in ___vsnprintf_chk (s=0x564e85b9e3b0 "the file \"o-\220\177", maxlen=<optimized out>, maxlen@entry=512, flags=flags@entry=1, slen=slen@entry=18446744073709551615, 
    format=format@entry=0x7f902c448ddd "the file \"%s\" because of \"%s\"", args=args@entry=0x7fffc1371f48) at vsnprintf_chk.c:63
#7  0x00007f902dc9cd34 in vsnprintf (__ap=0x7fffc1371f48, __fmt=0x7f902c448ddd "the file \"%s\" because of \"%s\"", __n=512, __s=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/stdio2.h:77
#8  elektraVFormat (format=format@entry=0x7f902c448ddd "the file \"%s\" because of \"%s\"", arg_list=arg_list@entry=0x7fffc1371f48)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/libs/elektra/internal.c:430
#9  0x00007f902c43f3bb in elektraAddWarningf36 (warningKey=warningKey@entry=0x564e85b09330, reason=0x7f902c448ddd "the file \"%s\" because of \"%s\"", 
    file=0x7f902c448578 "/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/resolver/resolver.c", line=0x7f902c448dd8 "1175", line=0x7f902c448dd8 "1175", 
    file=0x7f902c448578 "/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/resolver/resolver.c", reason=0x7f902c448ddd "the file \"%s\" because of \"%s\"")
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/obj-x86_64-linux-gnu/src/include/kdberrors.h:3458
#10 0x00007f902c43f4a4 in elektraUnlinkFile (filename=0x2 <error: Cannot access memory at address 0x2>, parentKey=parentKey@entry=0x564e85b09330)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/resolver/resolver.c:1175
#11 0x00007f902c440cc5 in libelektra_resolver_fm_hpu_b_fm_hpu_b_LTX_elektraPluginerror (handle=<optimized out>, r=<optimized out>, parentKey=0x564e85b09330)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/resolver/resolver.c:1191
#12 0x00007f9029b7cb2d in elektraMultifileError (handle=0x564e85a68a10, returned=0x564e85b80490, parentKey=0x564e85b09330)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/multifile/multifile.c:900
#13 0x00007f902deb2bf6 in elektraSetRollback (parentKey=0x564e85b09330, split=0x564e85b7b520) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/libs/elektra/kdb.c:1331
#14 kdbSet (handle=0x564e85a3dce0, ks=0x564e85b0c0c0, parentKey=0x564e85b09330) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/libs/elektra/kdb.c:1564
#15 0x0000564e84a3fc59 in kdb::KDB::set (parentKey=..., returned=..., this=0x564e85a3dc78)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/bindings/cpp/include/kdb.hpp:229
#16 CpCommand::execute (this=0x564e85a3dc70, cl=...) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/tools/kdb/cp.cpp:111
#17 0x0000564e84a23659 in main (argc=<optimized out>, argv=0x7fffc1372bd8) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/tools/kdb/main.cpp:198
```

### LINKED ISSUE #2780: resolver: solution on non-permission errors wrong
Segmentation fault when file descriptor limit is exceeded.

### PR DESCRIPTION
**Pull request by mpranj**
Closes #2780 and closes #2694.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [x] affected documentation is fixed
- [x] I added code comments, logging, and assertions (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))

## Review

Reviewers will usually check the following:

- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

File: src/plugins/multifile/multifile.c [hunk 1]
```diff
@@ -903,7 +907,7 @@ int elektraMultifileError (Plugin * handle ELEKTRA_UNUSED, KeySet * returned ELE
 		keySetString (parentKey, s->fullPath);
 		if (resolver->kdbError)
 		{
-			resolver->kdbError (handle, returned, parentKey);
+			resolver->kdbError (resolver, returned, parentKey);
```
Comment (mpranj) [inline src/plugins/multifile/multifile.c]: It's nice how something like this goes undetected for three years and multiple releases.

**Comment by mpranj** [comment]
@markus2330 done!

**Comment by markus2330** [comment]
Absolutely amazing! A **big** thanks for these two important fixes!
