### PR TITLE
crypto-plugin: add /usr/bin/gpg as second fallback

### LINKED ISSUE #940: crypto-plugin: try using /usr/bin/gpg as fallback too
# Problem

At the moment the crypto plugin (gpg module) tries to use `/usr/bin/gpg2` as fallback value (e.g. if the `PATH` variabel is empty). If `gnupg2` is not installed, the module fails to find the executable.

# Desired Behavior

The gpg module also looks for `/usr/bin/gpg` as fallback solution, if the lookup in `PATH` was unsuccessful.

# Why is it important?

We came across this issue when certain build agents failed to run the test cases. The `PATH` environment variable is empty when the build job runs. If `gnupg2` is not installed on the build agent, the test cases fail.

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

If the PATH environment variable is empty we check if `/usr/bin/gpg2` or `/usr/bin/gpg` is available as a fallback.

Fixes #940.

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by petermax2** [comment]
I opened an issue for the memory leak ( #942 ).

File: src/plugins/crypto/gpg.c [hunk 1]
```diff
@@ -166,16 +197,39 @@ static int getGpgBinary (char ** gpgBin, KeySet * conf, Key * errorKey)
 	}
 
 
-	// last resort
-	const size_t defaultLen = strlen (ELEKTRA_CRYPTO_DEFAULT_GPG_BIN) + 1;
-	*gpgBin = elektraMalloc (defaultLen);
+	// last resort number one - check for gpg2 at /usr/bin/gpg2
+	// NOTE this might happen if the PATH variable is empty
+	*gpgBin = strdup (ELEKTRA_CRYPTO_DEFAULT_GPG2_BIN);
```
Comment (markus2330) [inline src/plugins/crypto/gpg.c]: Please use elektraStrDup here.

And why use pointer to pointer? (not needed here, maybe you can put this fallback code to separate function altogether?)

File: src/plugins/crypto/gpg.c [hunk 2]
```diff
@@ -166,16 +197,39 @@ static int getGpgBinary (char ** gpgBin, KeySet * conf, Key * errorKey)
...
+	if (!(*gpgBin))
+	{
+		ELEKTRA_SET_ERROR (87, errorKey, "Memory allocation failed");
+		return -1;
+	}
+
+	if (isExecutable (*gpgBin, NULL) == 0)
+	{
+		return 1;
```
Comment (markus2330) [inline src/plugins/crypto/gpg.c]: There are memleaks (does not free gpgBin, also see below).

File: src/plugins/crypto/gpg.c [hunk 3]
```diff
@@ -327,18 +381,10 @@ int elektraCryptoGpgCall (KeySet * conf, Key * errorKey, Key * msgKey, char * ar
...
 	{
-		ELEKTRA_SET_ERRORF (ELEKTRA_ERROR_CRYPTO_GPG, errorKey, "gpg binary %s not found", argv[0]);
 		elektraFree (argv[0]);
-		return -1;
-	}
-
-	if (access (argv[0], X_OK))
-	{
-		ELEKTRA_SET_ERRORF (ELEKTRA_ERROR_CRYPTO_GPG, errorKey, "gpg binary %s has no permission to execute", argv[0]);
-		elektraFree (argv[0]);
```
Comment (markus2330) [inline src/plugins/crypto/gpg.c]: Why not free `argv[0]`?

File: src/plugins/crypto/gpg.c (hunk 2 above)
Comment (petermax2) [inline src/plugins/crypto/gpg.c]: No, `gpgBin` has to be freed by the caller. It gets deallocated only if an error occurs. Please see the doc of the method:

	/**
	 * @brief lookup the path to the gpg binary in conf.
	 * @param gpgBin holds allocated path to the gpg binary to be used or NULL in case of an error. Must bee freed by the caller.
	 * @param conf KeySet holding the plugin configuration.
	 * @param errorKey holds an error description if something goes wrong.
	 * @retval 1 on success.
	 * @retval -1 on error. In this case errorkey holds an error description.
	 */

File: src/plugins/crypto/gpg.c (hunk 3 above)
Comment (petermax2) [inline src/plugins/crypto/gpg.c]: It is freed or am I mistaking?

	// check that the gpg binary exists and that it is executable
	if (isExecutable (argv[0], errorKey) < 0)
	{
		elektraFree (argv[0]);
		return -1; // error set by isExecutable()
	}

File: src/plugins/crypto/gpg.c (hunk 2 above)
Comment (markus2330) [inline src/plugins/crypto/gpg.c]: I expected you checked for errors, not for success. Can you add a small comment there?

File: src/plugins/crypto/gpg.c (hunk 3 above)
Comment (markus2330) [inline src/plugins/crypto/gpg.c]: Sorry my fault, I did not look at the upper part of the diff.

File: src/plugins/crypto/gpg.c [hunk 4]
```diff
@@ -25,6 +25,37 @@ static inline void closePipe (int * pipe)
 }
 
 /**
+ * @brief checks whether or not a given file exists and is executable.
+ * @param file holds the path to the file that should be checked
+ * @param errorKey holds an error description if the file does not exist or if it is not executable. Ignored if set to NULL.
+ * @retval 1 if the file exists and is executable
```
Comment (petermax2) [inline src/plugins/crypto/gpg.c]: I can see how `0` indicating success can be confusing. I changed it to `1` to be consistent with the rest of the module.

**Comment by petermax2** [comment]
Thank you for the feedback. I restructured `getGpgBinary ()` a little bit. Hopefully the fallback logic is now easier to understand.

**Comment by markus2330** [comment]
Nice solution!
