### PR TITLE
cache: fix GCC ASAN Build Warnings, closes #2820

### LINKED ISSUE #2820: Cache: GCC ASAN Build Warnings
# Steps to Reproduce the Problem

1. Download the file [Dockerfile.txt](https://github.com/ElektraInitiative/libelektra/files/3386130/Dockerfile.txt) and store it as `scripts/docker/debian/buster/Dockerfile`

2. Build the Docker image

   ```sh
   docker build \
          -t elektra-buster \
          --build-arg JENKINS_USERID=$(id -u) \
          --build-arg JENKINS_GROUPID=$(id -g) \
          -f scripts/docker/debian/buster/Dockerfile \
          scripts/docker/debian/buster/
   ```

3. Run the Docker image

   ```sh
   docker run \
          -it --rm --cap-add SYS_PTRACE \
          -v "$PWD:/home/jenkins/workspace" \
          -w /home/jenkins/workspace \
          elektra-buster
   ```

4. Create the build system

   ```sh
   mkdir build
   cd build
   cmake \
         -DBUILD_DOCUMENTATION=OFF \
         -DCOMMON_FLAGS=-Werror \
         -DENABLE_ASAN=ON \
         -DBINDINGS='ALL;-DEPRECATED' \
         -DPLUGINS='ALL;-DEPRECATED ' \
         -DTOOLS='ALL;-qt-gui' \
         -DENABLE_DEBUG=ON \
         -DKDB_DB_FILE=default.mmap \
         -DKDB_DB_INIT=elektra.mmap \
         -DKDB_DEFAULT_STORAGE=mmapstorage \
         ..
   ```

5. Compile Elektra

   ```sh
   cmake --build .
   ```

# Expected Result

The build system is able to translate Elektra without any warnings.

# Actual Result

GCC `8.3` reports a warning about a null destination pointer:

```
src/plugins/cache/cache.c: In function ‘elektraCacheSet’:
src/plugins/cache/cache.c:154:8: error: null destination pointer [-Werror=format-overflow=]
  len = sprintf (tmpFile, "%s", cacheFileName);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

.

# System Information

- Elektra `master`
- Docker `2.0.0.3`

# Further Log Files and Output

- [Jenkins Build Job](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2819/11/pipeline/458)

### PR DESCRIPTION
**Pull request by mpranj**
Closes #2820.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [ ] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))

## Review

Reviewers will usually check the following:

- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

File: src/plugins/cache/cache.c [hunk 1]
```diff
@@ -151,7 +151,7 @@ static char * elektraGenTempFilename (char * cacheFileName)
 
 	tmpFilenameSize = strlen (cacheFileName) + POSTFIX_SIZE;
 	tmpFile = elektraCalloc (tmpFilenameSize);
-	len = sprintf (tmpFile, "%s", cacheFileName);
+	len = snprintf (tmpFile, strlen (cacheFileName), "%s", cacheFileName);
```
Comment (sanssecours) [inline src/plugins/cache/cache.c]: As far as I can tell, this line contains an off-by-one error. According to the documentation of `strlen` the function

> returns the number of characters that precede the terminating NUL character

. The function `snprintf` on the other hand

> will write at most size-1 of the characters printed into the output string (the size'th character then gets the terminating `\0')

. If we assume `cacheFileName` is `"one"`, then `strlen` returns `3`, while `snprintf` will write two characters and `'\0'`, effectively storing `"on"` in `tmpFile`.

**Comment by sanssecours** [comment]
I just pushed a commit that might fix the broken build jobs. Unfortunately I was unable to reproduce the segmentation faults locally, so I am not sure commit c93c40e really fixes the problem. Anyway, please feel free to delete my commit, if you do not like the changes.

**Comment by mpranj** [comment]
Thank you for fixing my oversight. I have no problem with the changes. I think it's ready to merge with your fix.
