### PR TITLE
fcrypt: try manual copy if rename () fails

### LINKED ISSUE #3283: testshell_markdown_tutorial_crypto: fail
## Steps to Reproduce the Problem

Build libelektra while having gpgme development files. (`gpgme-devel` on fedora)
I used
```
cmake -DBUILD_DOCUMENTATION=ON -DBINDINGS="ALL" -DBUILD_SHARED=ON -DBUILD_STATIC=ON -DBUILD_FULL=ON -DENABLE_COVERAGE=OFF -DENABLE_OPTIMIZATIONS=ON -DENABLE_DEBUG=ON -DENABLE_LOGGER=OFF -DBUILD_STATIC=ON -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DKDB_DB_SYSTEM="$SYSTEM_DIR" DCMAKE_INSTALL_PREFIX=./releaseInstallDir -DPLUGINS="ALL" -DTOOLS="ALL" ..
```
but not everything is relevant to the problem.

```sh
make run_all
```

## Expected Result

```
Test #215: testshell_markdown_tutorial_crypto ........... Passed    2.58 sec
```

## Actual Result

Seems that there is a problem with /tmp on tmpfs or similar? I get the problem on fedora and also on debian buster (in docker).

```
249/262 Test #215: testshell_markdown_tutorial_crypto ...........***Failed    2.58 sec
Input: /home/mpranj/workspace/libelektra/doc/tutorials/crypto.md
kdb mount test.ini user/tests ini
kdb set user/tests/password 1234
kdb file user/tests/password | xargs cat
kdb rm user/tests/password
kdb umount user/tests
kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
kdb set user/tests/password 1234

ERROR - RET:
Return value “5” does not match “0”

kdb file user/tests/password | xargs cat

ERROR - RET:
Return value “123” does not match “0”

kdb rm user/tests/password

ERROR - RET:
Return value “11” does not match “0”

kdb umount user/tests
kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
kdb set user/tests/password 1234

ERROR - RET:
Return value “5” does not match “0”

kdb file user/tests/password | xargs cat

ERROR - RET:
Return value “123” does not match “0”

kdb rm user/tests/password

ERROR - RET:
Return value “11” does not match “0”

kdb umount user/tests
kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
kdb set user/tests/password 1234

ERROR - RET:
Return value “5” does not match “0”

kdb file user/tests/password | xargs cat

ERROR - RET:
Return value “123” does not match “0”

kdb rm user/tests/password

ERROR - RET:
Return value “11” does not match “0”

kdb umount user/tests
kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
kdb meta-set user/tests/password crypto/encrypt 1
kdb set user/tests/password 1234
kdb set user/tests/unencrypted "I am not encrypted"
kdb file user/tests/password | xargs cat
kdb meta-set user/tests/password crypto/encrypt 0
kdb file user/tests/password | xargs cat
kdb rm user/tests/unencrypted
kdb rm user/tests/password
kdb umount user/tests
shell_recorder /tmp/tmp.FLYIzi6Q4K RESULTS: 31 test(s) done 9 error(s).

—— Protocol ————————————————————————————————————————————————————
CMD: kdb mount test.ini user/tests ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 0
STDOUT: Create a new key user/tests/password with string "1234"

CMD: kdb file user/tests/password | xargs cat
RET: 0
STDOUT: password=1234

CMD: kdb rm user/tests/password
RET: 0

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 5
=== FAILED return value does not match expected pattern 0
STDERR: Sorry, module fcrypt issued the error C01100:
Resource: Renaming file /tmp/test.ini.2110573:1574783987.412609.tmpZJttxQ to /home/mpranj/.config/test.ini.2110573:1574783987.412609.tmp failed. Reason: Invalid cross-device link
ERROR: C01100

CMD: kdb file user/tests/password | xargs cat
RET: 123
=== FAILED return value does not match expected pattern 0
STDERR: cat: /home/mpranj/.config/test.ini: No such file or directory

CMD: kdb rm user/tests/password
RET: 11
=== FAILED return value does not match expected pattern 0
STDERR: Did not find the key

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 5
=== FAILED return value does not match expected pattern 0
STDERR: Sorry, module fcrypt issued the error C01100:
Resource: Renaming file /tmp/test.ini.2110783:1574783987.564306.tmpRJuvgG to /home/mpranj/.config/test.ini.2110783:1574783987.564306.tmp failed. Reason: Invalid cross-device link
ERROR: C01100

CMD: kdb file user/tests/password | xargs cat
RET: 123
=== FAILED return value does not match expected pattern 0
STDERR: cat: /home/mpranj/.config/test.ini: No such file or directory

CMD: kdb rm user/tests/password
RET: 11
=== FAILED return value does not match expected pattern 0
STDERR: Did not find the key

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 5
=== FAILED return value does not match expected pattern 0
STDERR: Sorry, module fcrypt issued the error C01100:
Resource: Renaming file /tmp/test.ini.2111010:1574783987.747497.tmpti3bSR to /home/mpranj/.config/test.ini.2111010:1574783987.747497.tmp failed. Reason: Invalid cross-device link
ERROR: C01100

CMD: kdb file user/tests/password | xargs cat
RET: 123
=== FAILED return value does not match expected pattern 0
STDERR: cat: /home/mpranj/.config/test.ini: No such file or directory

CMD: kdb rm user/tests/password
RET: 11
=== FAILED return value does not match expected pattern 0
STDERR: Did not find the key

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
RET: 0

CMD: kdb meta-set user/tests/password crypto/encrypt 1
RET: 0

CMD: kdb set user/tests/password 1234
RET: 0
STDOUT: Set string to "1234"

CMD: kdb set user/tests/unencrypted "I am not encrypted"
RET: 0
STDOUT: Create a new key user/tests/unencrypted with string "I am not encrypted"

CMD: kdb file user/tests/password | xargs cat
RET: 0
STDOUT: unencrypted=I am not encrypted
#@META crypto/encrypt = 1
password=@BASE64IyFjcnlwdG8wMBEAAACCBjEzmVhqufXSsgK4VPRDUC9GyQxBhocVbgZwimonK+xHaRCSX/blNDSVdIoSRg0n

CMD: kdb meta-set user/tests/password crypto/encrypt 0
RET: 0

CMD: kdb file user/tests/password | xargs cat
RET: 0
STDOUT: unencrypted=I am not encrypted
#@META crypto/encrypt = 0
password=1234

CMD: kdb rm user/tests/unencrypted
RET: 0

CMD: kdb rm user/tests/password
RET: 0

CMD: kdb umount user/tests
RET: 0
————————————————————————————————————————————————————————————————

```

## System Information

- Elektra Version: master
- Operating System: Fedora
- Versions of other relevant software?

### PR DESCRIPTION
**Pull request by petermax2**
rename () accross file systems is not supported and causes failures.
If rename () fails, fcrypt tries to perform a manual copy.

See #3283 for full discussion.

Fixes #3283 .

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

File: src/plugins/fcrypt/fcrypt.c [hunk 1]
```diff
@@ -230,15 +234,29 @@ static int fcryptGpgCallAndCleanup (Key * parentKey, KeySet * pluginConfig, char
...
+				readCount = read (tmpFileFd, buffer, sizeof (buffer));
+			}
+			manualCopy = 1;
 		}
 	}
 
 	if (result == 1)
 	{
-		if (parentKeyFd >= 0)
+		if (parentKeyFd >= 0 && !manualCopy)
```
Comment (mpranj) [inline src/plugins/fcrypt/fcrypt.c:259]: Is there harm in shredding anyway? The fact that rename failed but the content could be copied does not guarantee that it was in ramdisk. I don't know how ramdisk works but it is not a bad idea to also overwrite sensitive data in ram.

Comment (petermax2) [reply src/plugins/fcrypt/fcrypt.c:259]: `parentKeyFd` holds the "target" data, so we would shred the content that we manually copied before. I do not remember why I introduced this shred in the first place. But I think in case of `manualCopy` the `tmpFile` should be unlinked. I will check this tomorrow.

File: doc/news/_preparation_next_release.md [hunk 2]
```diff
@@ -53,6 +53,10 @@ The following section lists news about the [modules](https://www.libelektra.org/
 
 - The plugin now only interprets a key set as [array](../tutorials/arrays.md) if the parent contains the meta key `array`. _(René Schwaiger)_
 
+### Fcrypt
+
+- Improve handling of temporary files after encryption and decryption by trying to perform a manual copy if the call of `rename` fails. Tis problem might occur if `/tmp` is mounted to a another file system. _(Peter Nirschl)_
```
Comment (markus2330) [inline doc/news/_preparation_next_release.md:58]:
```suggestion
- Improve handling of temporary files after encryption and decryption by trying to perform a manual copy if the call of `rename` fails. This problem might occur if another file system is mounted on `/tmp`. _(Peter Nirschl)_
```

File: src/plugins/fcrypt/fcrypt.c [hunk 3]
```diff
@@ -230,15 +234,29 @@ static int fcryptGpgCallAndCleanup (Key * parentKey, KeySet * pluginConfig, char
...
 		if (rename (tmpFile, keyString (parentKey)) != 0)
 		{
-			ELEKTRA_SET_RESOURCE_ERRORF (parentKey, "Renaming file %s to %s failed. Reason: %s", tmpFile, keyString (parentKey),
-						     strerror (errno));
-			result = -1;
+			// if rename failed we can still try to copy the file content manually
+			lseek (tmpFileFd, 0, SEEK_SET);
+			lseek (parentKeyFd, 0, SEEK_SET);
+			readCount = read (tmpFileFd, buffer, sizeof (buffer));
+			while (readCount > 0)
```
Comment (markus2330) [inline src/plugins/fcrypt/fcrypt.c:241]: Silent errors of read? (and also lseek?)

File: src/plugins/fcrypt/fcrypt.c [hunk 4]
```diff
@@ -230,15 +234,29 @@ static int fcryptGpgCallAndCleanup (Key * parentKey, KeySet * pluginConfig, char
...
+			{
+				writeCount = write (parentKeyFd, buffer, readCount);
+				if (writeCount != readCount)
```
Comment (markus2330) [inline src/plugins/fcrypt/fcrypt.c:244]: This check is too strict, it is perfectly okay when write does not write everything at once but only a junk. Be beware of not introducing silent errors here.

File: doc/news/_preparation_next_release.md (hunk 2 above)
Comment (sanssecours) [reply doc/news/_preparation_next_release.md:58]: The suggestion sounds good, although I would replaces “on” with “at”.

```suggestion
- Improve handling of temporary files after encryption and decryption by trying to perform a manual copy if the call of `rename` fails. This problem might occur if another file system is mounted at `/tmp`. _(Peter Nirschl)_
```

Comment (markus2330) [reply doc/news/_preparation_next_release.md:58]: Maybe we should also replace the "on" with "at" on the output of `kdb mount`?

Comment (markus2330) [reply doc/news/_preparation_next_release.md:58]: `mount` also uses "on", though.

File: src/plugins/fcrypt/fcrypt.c [hunk 5]
```diff
@@ -235,20 +235,55 @@ static int fcryptGpgCallAndCleanup (Key * parentKey, KeySet * pluginConfig, char
 		if (rename (tmpFile, keyString (parentKey)) != 0)
 		{
 			// if rename failed we can still try to copy the file content manually
-			lseek (tmpFileFd, 0, SEEK_SET);
-			lseek (parentKeyFd, 0, SEEK_SET);
+			if (lseek (tmpFileFd, 0, SEEK_SET))
+			{
+				ELEKTRA_SET_RESOURCE_ERRORF (
```
Comment (markus2330) [inline src/plugins/fcrypt/fcrypt.c:240]: Why not a single "ELEKTRA_SET_RESOURCE_ERRORF" at the very end? (errno must be saved, though)

File: src/plugins/fcrypt/fcrypt.c [hunk 6]
```diff
@@ -260,6 +295,18 @@ static int fcryptGpgCallAndCleanup (Key * parentKey, KeySet * pluginConfig, char
 		{
 			shredTemporaryFile (parentKeyFd, parentKey);
 		}
+		if (manualCopy)
```
Comment (markus2330) [inline src/plugins/fcrypt/fcrypt.c:298]: Shouldn't we also shred in case of failed copies?

Comment (petermax2) [reply src/plugins/fcrypt/fcrypt.c:298]: It's handled in the "else"-branch one level above. But I see how I could simplify this code segment.

File: doc/news/_preparation_next_release.md (hunk 2 above)
Comment (sanssecours) [reply doc/news/_preparation_next_release.md]: > `mount` also uses "on", though.

After a little bit of research, I now also think that “on” seems to be the right preposition.

Comment (petermax2) [reply doc/news/_preparation_next_release.md]: OK then I'll change it back to "on" after the build server is done.

**Comment by petermax2** [comment]
Seems like MMap ran into a timeout.

**Comment by mpranj** [comment]
I triggered a rebuild. I think you should be able to trigger rebuilds if you login to cirrus with your GitHub, fyi.

**Comment by petermax2** [comment]
> I triggered a rebuild. I think you should be able to trigger rebuilds if you login to cirrus with your GitHub, fyi.

Yes, you are right. I also have permissions to trigger a re-build. Thanks!

I think I'm ready for merge, if there are not further objections.

**Comment by mpranj** [comment]
@petermax2 thank you so much for fixing this!
