### PR TITLE
website: fix markdown link detection and render KEYNAMES.md

### LINKED ISSUE #3646: keynames link broken
As reported by Ferdinand Thommes, the link to KEYNAMES.md in the release notes as rendered by the website is broken. I think this is because this is not a page automatically indexed nor manually added in the website structure. (Subfolders of doc are added, but not files in the doc folder itself.)

Fix: move the file to `doc/dev`, as initially suggested by me but unfortunately this breaks the link on GitHub release pages, where it works now... I hope we can avoid such special cases in the future.

@kodebach do you have time to fix it?

### PR DESCRIPTION
**Pull request by kodebach**
Fixes #3646 

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

File: src/tools/website/resources/grunt-tasks/grunt-copy-website-content.js [hunk 1]
```diff
@@ -158,7 +158,7 @@ module.exports = function(grunt) {
       };
 
       this.ensureAbsoluteLinkPaths = function(filepath, text) {
-        return text.replace(/\[(.+)\]\(([^\)]+)\)/gi, function(
+        return text.replace(/\[([^\]]+)\]\(([^\)]+)\)/gi, function(
```
Comment (kodebach) [inline src/tools/website/resources/grunt-tasks/grunt-copy-website-content.js:161]: @markus2330 The issue actually wasn't that `doc/KEYNAMES.md` was not listed in `structure.json.in` (although I fixed that as well). The issue was that we don't use a proper markdown parser and this Regex only worked, if there was just one link per line.

See also: https://regex101.com/r/OeDKOS/1

**Comment by kodebach** [comment]
@mpranj Please, merge ASAP. I will try and keep an eye on the build servers, but if something is broken and I don't notice, just tag me in a comment.

**Comment by mpranj** [comment]
Thank you for the quick fix!

The website build already started, I will wait to see if it builds successfully and merge.
