### PR TITLE
list: fix for #1855

### LINKED ISSUE #1855: bug: list plugin & nested plugin configuration
I believe there is a bug in list plugin which which prevents configuration for globally mounted plugins.
I could reproduce the steps on 0.8.22.

## Steps to Reproduce the Problem

Step by step guide on how to reproduce the problem:

```sh
kdb gmount dbus announce=once

# monitor system bus in another shell
dbus-monitor --system

kdb set sytem/foo/bar 123
#> Create a new key system/foo/bar with string "123"
```

When using the plugin at a mountpoint everything works well.

## Expected Result

The dbus monitor should report "Commit" events since "announce=once" configured it to do so.

## Actual Result

The dbus monitor reports "KeyAdded" or "KeyChanged" events.
I was able to reproduce this with other plugins (zeromqsend & zeromqrecv from PR #1835) as well.

## System Information

- Elektra Version: master, 0.8.22

### PR DESCRIPTION
**Pull request by waht**
# Purpose

This PR should fix #1855.

# Checklist

- [x] commit messages are fine (with references to issues)
- [x] I *updated* unit tests
- [x] I ran all tests and everything went fine
- [x] affected documentation is fixed
- [x] I added code comments, logging, and assertions (see doc/CODING.md)
- [x] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by waht** [comment]
jenkins build all please

**Comment by waht** [comment]
jenkins build multiconfig-gcc-stable please

File: src/plugins/list/list.c [hunk 1]
```diff
@@ -306,21 +306,29 @@ static int runPlugins (KeySet * pluginKS, KeySet * modules, KeySet * plugins, Ke
...
+				// append system config to plugin?
+				// seems like it is not used anymore
+				// TODO remove?
+				/*Key * toRemove = keyNew ("user/plugins", 0);
 				ksDel (ksCut (sysConfigAll, toRemove));
-				ksAppend (realPluginConfig, sysConfigAll);
-				keyDel (toRemove);
-				toRemove = keyNew ("user/placements", 0);
-				ksDel (ksCut (realPluginConfig, toRemove));
-				ksRewind (realPluginConfig);
```
Comment (waht) [inline src/plugins/list/list.c]: This code seems unused and without function. I tried to use it by setting `system/elektra/globalplugins/system/plugins/#1/config/...` instead of `system/elektra/globalplugins/user/plugins/#1/config/...` but it seems like the backend did not pass it to the list plugin.
@markus2330 or @tom-wa can you remember what the use case for this was?

Comment (markus2330) [reply src/plugins/list/list.c]: Only @tom-wa was involved in this implementation. I just read his docu and implemented backend.cpp accordingly. See #1855

Comment (tom-wa) [reply src/plugins/list/list.c]: @waht 
>can you remember what the use case for this was?

everything below `system` was passed as system config to all plugins, while `user/plugins/#1/config` was only passed to plugin `#1`

Comment (waht) [reply src/plugins/list/list.c]: Ok I see. I changed it so that common plugin config can be passed using "/config" and added documentation for it. It should be usable now when mounting manually as well.

**Comment by waht** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
Is this ready for review? (remove "work in progress" if it is) Please rebase after the release.

**Comment by waht** [comment]
jenkins build all please

File: src/plugins/list/testmod_list.c [hunk 2]
```diff
@@ -51,7 +53,7 @@ static void doTest (void)
 	elektraPluginClose (check, 0);
 
 	succeed_if (plugin->kdbGet (plugin, ks, parentKey) == 1, "kdbget failed");
-	const Key * key = ksLookupByName (ks, "user/tests/list/meta1", 0);
+	const Key * key = ksLookupByName (ks, "user/tests/list/META1", 0);
```
Comment (markus2330) [inline src/plugins/list/testmod_list.c]: Does this test trigger the bug now?

File: doc/news/_preparation_next_release.md [hunk 3]
```diff
@@ -88,6 +88,9 @@ We added even more functionality, which could not make it to the highlights:
 ## Other News
 
 - The `crypto` plugin now uses Elektra's `libinvoke` and the `base64` plugin in order to encode and decode Base64 strings. This improvement reduces code duplication between the two plugins. *(Peter Nirschl)*
+- The [`list` plugin](http://libelektra.org/plugins/list) now allows to pass
```
Comment (markus2330) [inline doc/news/_preparation_next_release.md]: "allows us".

File: doc/news/_preparation_next_release.md [hunk 4]
```diff
@@ -88,6 +88,9 @@ We added even more functionality, which could not make it to the highlights:
...
+  common configuration for plugins below the "config/" setting. The updated
```
Comment (markus2330) [inline doc/news/_preparation_next_release.md]: What about something like:

for plugins below the "config/" setting
->
for all plugins by using keys below the "config/" setting

File: src/plugins/list/testmod_list.c (hunk 2 above)
Comment (waht) [reply src/plugins/list/testmod_list.c]: Yes, line 27 configures the rename plugin directly to cut a part of the key name ("to/be/cut"), while line 34 configures every plugin with "config/toupper" which is only used by the rename plugin.

Comment (waht) [reply src/plugins/list/testmod_list.c]: I added comments for this to the test.

**Comment by waht** [comment]
jenkins build all please

**Comment by waht** [comment]
jenkins build libelektra please

**Comment by waht** [comment]
jenkins build ini-mergerequests please

**Comment by sanssecours** [comment]
> jenkins build ini please

The build job `elektra-ini-mergerequests` is currently broken. Pull request #2028 contains a [fix](https://github.com/ElektraInitiative/libelektra/pull/2028/commits/fe4e1150b250cc80c17e5c8ba8c4393bfad3e8e7).

**Comment by markus2330** [comment]
Thank you for the great work!
